import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const runtime = "edge";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // let's do some server side logic here
  const worldtimeapiFetch = await fetch('http://worldtimeapi.org/api/timezone/Europe/London');
  const worldtimeapiJson: {
    day_of_year: number;
  } = await worldtimeapiFetch.json();

  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='main-layout'>
        <p>main layout (current day of year: {worldtimeapiJson.day_of_year})</p>
        <div className='main-layout-children'>
          {children}
        </div>
      </div>
      </body>
    </html>
  )
}
